### ISSUE TITLE
素手で殴るとエラー？

### ISSUE THREAD

**Issue by kotarobo** [SakuraServerDevTeam/FlagGame#33]
素手で攻撃するとキルログが残らない他ログにエラーが流れる

**Comment by 4oi** [comment]
ごめんなさい，エラーログがないと問題箇所が把握できませんでした．
エラーログとともに再報告をお願いします．
また，問題と思しき箇所はbeta7で変更が加えられています．
バージョンを併記してください．

**Comment by 4oi** [comment]
https://github.com/SakuraServerDevTeam/FlagGame/commit/a5d0c9325d3e9dea0ca914c14715b7a3f7fd2714
