### ISSUE TITLE
募集中に両チーム参加者がわかるようにしてほしい

### ISSUE THREAD

**Issue by kotarobo** [SakuraServerDevTeam/FlagGame#34]
人数が一致した時点で開催するように注意はしているけども、チャットログで流れる事もあるので人数が確認できる方法がほしい

**Comment by 4oi** [comment]
2.0beta10 https://github.com/SakuraServerDevTeam/FlagGame/commit/fd2c191138837f4ba012a84667f0787a8b5f2862 にて,参加者に対して人数を通知するよう機能を追加いたしました．
ただし，主催者へは通知されないため，今後のアップデートで対応していきます
